### ISSUE TITLE
"Import praw" does not work

### ISSUE THREAD

**Issue by KimKirk** [csu/export-saved-reddit#13]
Ran the script, received this message:
 
  import praw
ImportError: No module named praw

Searched for "praw" and found none. Please advise next step.

**Comment by rachmadaniHaryono** [comment]
Have you pip install the required package? 

Other way you can install it can be seen here 

https://praw.readthedocs.io/en/v4.0.0rc3/getting_started/installation.html

**Comment by csu** [comment]
The [installation instructions in the README ](https://github.com/csu/export-saved-reddit#installation) say to run `pip install` which installs `praw`.

**Comment by KimKirk** [comment]
Got it to work; thank you!
