### ISSUE TITLE
traceback errors trying to run exposed-saved.py

### ISSUE THREAD

**Issue by Bill565** [csu/export-saved-reddit#18]
This is what I'm getting from cmd:

C:\Users\Bill\export-saved-reddit>python export-saved.py
Traceback (most recent call last):
  File "export-saved.py", line 148, in <module>
    main()
  File "export-saved.py", line 81, in main
    r = praw.Reddit(user_agent='export saved 1.0')
  File "F:\Program Files (x86)Python27\lib\site-packages\praw\reddit.py", line 114, in __init__
    raise ClientException(required_message.format(attribute))
praw.exceptions.ClientException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.

Any help is appreciated! Fairly inexperienced with programming.

**Comment by rachmadaniHaryono** [comment]
What is the version of your praw module?

**Comment by Bill565** [comment]
4.0.0

**Comment by rachmadaniHaryono** [comment]
can you run it in virtualenv and use praw 3.3?

the script is not yet update for praw 4.0 and the praw update require oauth authentification. 

https://praw.readthedocs.io/en/latest/getting_started/authentication.html#script-application

it require @csu to register the application and put the client id and secret it program. (although you or any user can do it to)

**Comment by csu** [comment]
Yeah, the solution here is to use praw 3.3.0, as specified in the project's `requirements.txt` file. Looks like plain text user/pass authentication was deprecated in praw 4.0.0. I'll consider somehow altering the script to use OAuth instead (but then, as @rachmadaniHaryono, users might need to supply a client id/secret, which would make the setup more complicated).

**Comment by Bill565** [comment]
I initially installed praw 3.3.0 but when I tried to run the script I got this error: "Version 3.3.0 of praw is outdated. Version 4.0.0 was released Tuesday November 29, 2016." and cmd just hanged. Any idea?

**Comment by csu** [comment]
It might be running correctly, just silently, Try running the script with
the `-v` (verbose) tag and see if you get any output (you can use `--help`
to view all possible flags).

**Comment by Bill565** [comment]
You're right of course, everything works fine. It just takes a minute for the html file to appear. No error here, my mistake. Thank you!
