### ISSUE TITLE
Can't deal with non-ascii characters

### ISSUE THREAD

**Issue by pixlark** [csu/export-saved-reddit#30]
When the scripts encounters a saved post with a title containing a non-ascii character, it displays the error "UnicodeEncodeError: 'ascii' codec can't encode characters in position 42-44: ordinal not in range(128)"

**Comment by pixlark** [comment]
putting an Except UnicodeEncodeError on the csvwriter.writerow(row) seems to fix this, for my purposes at least.

**Comment by csu** [comment]
Thanks for reporting this. Should be fixed in commit 067df88.
