### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by LitePenguins** [csu/export-saved-reddit#37]
![error](https://cloud.githubusercontent.com/assets/11067464/24777049/3a8320da-1ae9-11e7-856d-b31978d6f19e.PNG)

**Comment by tosaddler** [comment]
I just had this same error as well.

**Comment by rachmadaniHaryono** [comment]
Which python version?

**Comment by LitePenguins** [comment]
I get this error on my Surface running Python 3.6 and my main desktop running Python 3.5.

**Comment by rachmadaniHaryono** [comment]
@LitePenguins and @tosaddler i have made fix on #38 can you test it?

**Comment by LitePenguins** [comment]
Deleting line 233 and adding the 4 new lines gives

![image](https://cloud.githubusercontent.com/assets/11067464/24890177/ec696762-1e33-11e7-90a7-3ba7c06ea2bb.png)

**Comment by rachmadaniHaryono** [comment]
i'm still fixing that. but with the last commit and succes test from travis ci may fix your issue. 

could you try that once again?

recent commit https://github.com/csu/export-saved-reddit/pull/38/commits/ae4561b3663a45fd8ebb59ddfd16f25c848215d9

**Comment by tosaddler** [comment]
I tried the change in that commit, was still getting the same error.

**Comment by rachmadaniHaryono** [comment]
@tosaddler can you post the error please?

**Comment by tosaddler** [comment]
`Traceback (most recent call last):
  File "export_saved.py", line 234, in write_csv
    csvwriter.writerow(csv_fields)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_saved.py", line 312, in <module>
    main()
  File "export_saved.py", line 306, in main
    save_saved(reddit)
  File "export_saved.py", line 274, in save_saved
    process(reddit, seq, "export-saved", "Reddit - Saved")
  File "export_saved.py", line 256, in process
    write_csv(csv_rows, file_name + ".csv")
  File "export_saved.py", line 242, in write_csv
    csvwriter.writerow(row)
  File "C:\Users\Trey\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 82-83: character maps to <undefined>`

After updating recent commit ae4561b still having this error.

**Comment by csu** [comment]
@tosaddler Is this on Windows?

@rachmadaniHaryono I suspect this bug might be on Windows. Unfortunately, Travis CI doesn't seem to support testing on Windows (does do Mac though, apparently!).

**Comment by tosaddler** [comment]
Yes, I was previously running the script on Windows.

![2017-04-12 08_55_05-tsaddler thinkstation_](https://cloud.githubusercontent.com/assets/13705399/24958636/fda66a86-1f5d-11e7-8c89-8e7e1b0e10f0.png)

Tried [ae4561b](https://github.com/csu/export-saved-reddit/commit/ae4561b3663a45fd8ebb59ddfd16f25c848215d9) on Ubuntu 16.04, Python 3.5, still experiencing this error.

**Comment by rachmadaniHaryono** [comment]
@csu &  @tosaddler I suspect before @tosaddler last test on ubuntu he just not only in windows but also python2.7

@csu I have Internet problem which make me can't use laptop right now. So I may not be able to continue to fix it. 

Maybe add try except and decode the string to bytes.

**Comment by ossvirt** [comment]
Hi, I seem to have the same error

`File "export_saved.py", line 305, in <module>
    main()
  File "export_saved.py", line 299, in main
    save_saved(reddit)
  File "export_saved.py", line 267, in save_saved
    process(reddit, seq, "export-saved", "Reddit - Saved")
  File "export_saved.py", line 249, in process
    write_csv(csv_rows, file_name + ".csv")
  File "export_saved.py", line 233, in write_csv
    csvwriter.writerow(csv_fields)
TypeError: 'str' does not support the buffer interface
`

Python 3.4.3 on Ubuntu 14.04

**Comment by rachmadaniHaryono** [comment]
@LitePenguins , @ossvirt , @tosaddler can you try the latest commit https://github.com/csu/export-saved-reddit/pull/38/commits/5d2ca4b6852dd482b20ed4558d30c9767d7fcdca?

for now try it on linux with python3. this issue on windows and python2.7 can be fixed later

also cc @nmandal and @netfortius to try with python2.7 for their own issue.

**Comment by tosaddler** [comment]
It now works properly when only exporting "saved", however one of my interests in this script was being able to export saved comments as well, which is buried in the -all parameter. When I run it with that option, it successfully exports saved, upvoted, and submission, but it has failed in the same spot twice now while trying to export saved comments.

![image](https://cloud.githubusercontent.com/assets/13705399/25138464/91b65672-2428-11e7-9096-a7bd472d2623.png)

Making progress though, I was at least able to save a lot of stuff from my profile! The saved comments are also very important to me though.

Is there any way to have each parameter separated, like only being able export comments, submitted, upvoted, by themselves?

**Comment by rachmadaniHaryono** [comment]
@tosaddler I think it warrant a new issue for that feature. 

Even if the new feature created, it have to wait till the pr for this issue is tested by user and merged by @csu. 

For the pr itself, I think it should be simple to implement
