### ISSUE TITLE
received 401 HTTP response

### ISSUE THREAD

**Issue by chipweinberger** [csu/export-saved-reddit#48]
As far as I can tell, my app secret, id password, and username are all correct. I tried both with the command line options and with the file loaded options.

maybe related to this https://www.reddit.com/r/redditdev/comments/6myq1h/praw_401_http_response_for_all_requests/

python export_saved.py -u xxxxx -p xxxxx -id xxxxx -s xxxxx -v
INFO:root:Login succesful
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.reddit.com
DEBUG:urllib3.connectionpool:https://www.reddit.com:443 "POST /api/v1/access_token HTTP/1.1" 401 41
Traceback (most recent call last):
  File "export_saved.py", line 336, in <module>
    main()
  File "export_saved.py", line 330, in main
    save_saved(reddit)
  File "export_saved.py", line 292, in save_saved
    seq = reddit.user.me().saved(limit=None)
  File "/Library/Python/2.7/site-packages/praw/models/user.py", line 60, in me
    user_data = self._reddit.get(API_PATH['me'])
  File "/Library/Python/2.7/site-packages/praw/reddit.py", line 320, in get
    data = self.request('GET', path, params=params)
  File "/Library/Python/2.7/site-packages/praw/reddit.py", line 404, in request
    params=params)
  File "/Library/Python/2.7/site-packages/prawcore/sessions.py", line 135, in request
    self._authorizer.refresh()
  File "/Library/Python/2.7/site-packages/prawcore/auth.py", line 328, in refresh
    password=self._password)
  File "/Library/Python/2.7/site-packages/prawcore/auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "/Library/Python/2.7/site-packages/prawcore/auth.py", line 31, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

**Comment by csu** [comment]
From [the Reddit API documentation](https://github.com/reddit/reddit/wiki/OAuth2#retrieving-the-access-token), it sounds like the 401 error is given when your client id/secret are incorrect. Are you using the correct values from the app page?

![](https://i.imgur.com/CSqaFkO.png)

**Comment by chipweinberger** [comment]
Ahhh, good thing I double checked. Despite copy pasting it, I had an error in the id.

A note to mac users, copy pasting can somtimes change the quote marks to tick marks..

**Comment by Dogy06** [comment]
Thanks :D

**Comment by DudeFr0mMars** [comment]
Hi  am still getting the same error . I double checked my client_id,secret and user_agent, they are all correct. What could be the reason of getting this error now? I am doing the same thing - scraping reddit for keywords .

**Comment by Harzh139** [comment]
> Hi am still getting the same error . I double checked my client_id,secret and user_agent, they are all correct. What could be the reason of getting this error now? I am doing the same thing - scraping reddit for keywords .

did it worked for u?? now im getting the same 401 error
