### ISSUE TITLE
praw version issues

### ISSUE THREAD

**Issue by ludovicaelbrecht** [csu/export-saved-reddit#5]
Hi,

Thanks for creating this. However, it doesn't work for me.

I've done the pip install. I renamed the example AccountDetails file to AccountDetails.py (and filled in username + password).

When executing it, I'm seeing this error message (using Python 2.7.9):

```python
λ C:\Applications\Python27\python export-saved.py
Traceback (most recent call last):
  File "export-saved.py", line 72, in <module>
    main()
  File "export-saved.py", line 59, in main
    r.login(AccountDetails.REDDIT_USERNAME, AccountDetails.REDDIT_PASSWORD)
  File "C:\Applications\Python27\lib\site-packages\praw\__init__.py", line 1266, in login
    self.user = self.get_redditor(user)
  File "C:\Applications\Python27\lib\site-packages\praw\__init__.py", line 890, in get_redditor
    return objects.Redditor(self, user_name, *args, **kwargs)
  File "C:\Applications\Python27\lib\site-packages\praw\objects.py", line 663, in __init__
    fetch, info_url)
  File "C:\Applications\Python27\lib\site-packages\praw\objects.py", line 72, in __init__
    self.has_fetched = self._populate(json_dict, fetch)
  File "C:\Applications\Python27\lib\site-packages\praw\objects.py", line 127, in _populate
    json_dict = self._get_json_dict() if fetch else {}
  File "C:\Applications\Python27\lib\site-packages\praw\objects.py", line 120, in _get_json_dict
    as_objects=False)
  File "C:\Applications\Python27\lib\site-packages\praw\decorators.py", line 161, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "C:\Applications\Python27\lib\site-packages\praw\__init__.py", line 526, in request_json
    data = json.loads(response, object_hook=hook)
  File "C:\Applications\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Applications\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Applications\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Any clue as to what could be wrong?

Thanks!

**Comment by ludovicaelbrecht** [comment]
Actually the login issue is resolved by updating praw. I change requirements.txt to use praw 3.3.0, and login now seems successful.

However, the API of praw seems to have changed, as I'm now seeing this issue with praw:

```python
λ C:\Applications\Python27\python export-saved.py
:0: UserWarning: The keyword `bot` in your user_agent may be problematic.
C:\Applications\Python27\lib\site-packages\praw\decorators.py:74: DeprecationWarning: reddit intends to disable password-based authentication of API clients sometime in the near future. As a result this method will be removed in a future major version of PRAW.

For more information please see:

* Original reddit deprecation notice: https://www.reddit.com/comments/2ujhkr/

* Updated delayed deprecation notice: https://www.reddit.com/comments/37e2mv/

Pass ``disable_warning=True`` to ``login`` to disable this warning.
  warn(msg, DeprecationWarning)
Traceback (most recent call last):
  File "export-saved.py", line 72, in <module>
    main()
  File "export-saved.py", line 64, in main
    export_csv += ("%s,%s,,%s\n" % (i.permalink.encode('utf-8'), i.title.encode('utf-8'), str(i.subreddit)))
  File "C:\Applications\Python27\lib\site-packages\praw\objects.py", line 84, in __getattr__
    attr))
AttributeError: '<class 'praw.objects.Submission'>' has no attribute 'subreddit'
```

Ideas?

Tnx!

**Comment by ludovicaelbrecht** [comment]
I looked into the praw API docs, specifically https://praw.readthedocs.org/en/PRAW-1.0.9/praw.html#praw.objects.Submission , but I don't see whether the attribute 'subreddit' has been renamed or whether it's no longer there. But I don't see the attribute 'title' or 'permalink' either for that class, so I'm probably reading the docs incorrectly...

Anyway, replacing `str(i.subreddit)` with the string `"subreddit"` allows me to get past that issue (though I'll obviously lose the breaking down by subreddit).

That allows me to get the CSV generated. I noticed 2 issues with the CSV:
(1) long titles don't work. Not sure what the issue is, but long titles get broken up into several array elements.
(2) the CSV is comma separated, but titles can contain commas too. Semicolons would occur less frequently, but still occur every now and then. A TSV file (tab separated values) would work though. I replaced the commas with a `\t` to generate a tab, and that works much better.

After generating the CSV (so before changing it to tabs), the conversion to HTML fails. This occurs either due to titles containing commas, or due to long titles -- not sure which.

Hope this helps, should you consider looking into getting this app working again.

Cheers

**Comment by ludovicaelbrecht** [comment]
Actually, turns out that the attribute "subreddit" still exists in praw. The issue is with handling a corner case: saved links that don't have a subreddit.

E.g. if you were to save https://www.reddit.com/comments/yz7pe/compare_our_science_videos_to_khan_academys_so/ , you'd get an exception because this link has no subreddit.

**Comment by rachmadaniHaryono** [comment]
hi, i made a fix on #6 by writing csv with its module. 

>Actually, turns out that the attribute "subreddit" still exists in praw. The issue is with handling a corner case: saved links that don't have a subreddit.

>E.g. if you were to save >https://www.reddit.com/comments/yz7pe/compare_our_science_videos_to_khan_academys_so/ , you'd get an exception because this link has no subreddit.

maybe because this is still count as comment not link, which will be filtered on the first loop.

**Comment by oolongtea** [comment]
Upgrading to praw 3.3.0 fixed this error for me. Using code from commit:

```
$ git rev-parse HEAD
57840ff28f91798e36e6da054a12a83d21602ddd
```

**Comment by csu** [comment]
@oolongtea thanks! I'll update `requirements.txt`

**Comment by csu** [comment]
Closing this issue for now. Feel free to comment if you're still having problems.
