### ISSUE TITLE
ModuleNotFoundError: No module named 'praw'

### ISSUE THREAD

**Issue by itripley** [csu/export-saved-reddit#51]
Forgive me for being a noob but I can't run instruction #4 "Back in your shell, run python export_saved.py in the export-saved-reddit folder". It gives me this "Traceback (most recent call last):
  File "export_saved.py", line 15, in <module>
    import praw
ModuleNotFoundError: No module named 'praw'"

**Comment by rachmadaniHaryono** [comment]
can you try run `pip install praw==4.4.0` ?

**Comment by NemanjaMilosevic** [comment]
Did you run  `pip install -r requirements.txt` ?

**Comment by itripley** [comment]
you guys were right, thank you
