### ISSUE TITLE
Praw is required

### ISSUE THREAD

**Issue by reddit-is-fun** [csu/export-saved-reddit#9]
After running **python export-saved.py** in terminal:

````
python export-saved.py  
Traceback (most recent call last):  
  File "export-saved.py", line 13, in <module>  
    import praw   
ImportError: No module named praw
````

It seems that [Praw] (https://praw.readthedocs.org/en/stable/) is required. I was able to run this script only after installing The Python Reddit Api Wrapper.  
If this is correct, please add Praw to 'requirements'.

**Comment by csu** [comment]
It's already there... https://github.com/csu/export-saved-reddit/blob/master/requirements.txt

**Comment by csu** [comment]
If you follow the installation instructions, it will handle the dependencies. This is why `pip` is in the requirements section.

**Comment by reddit-is-fun** [comment]
I followed the instructions, I don't know why I had to install Praw manually. I did ran "pip install -r requirements.txt":
